### PR TITLE
[9.0][REM] move res_currency_print_on_check got moved to account-payment repository

### PR DESCRIPTION
**Pull request by osvalr**
Move module `res_currency_print_on_check` from here to `account-payment` repository. 

This module is useful for accounting and payments, no l10n is included so that's why we think it's better to be there.

### CODE REVIEW

**Comment by osvalr** [comment]
Hi @joaoalf @hsoft,

 your comments are welcomed

**Comment by joaoalf** [comment]
@osvalr I'm OK with the move.

**Comment by joaoalf** [comment]
@Ehtaga @dufresnedavid ping

**Comment by ghost** [comment]
:+1:

**Comment by osvalr** [comment]
thank you @dufresnedavid

**Pull request merged**
