### PR TITLE
7.0 ddufresne income tax deductions

### PR DESCRIPTION
**Pull request by ghost**
Added module for canada income tax deductions. Will be used in l10n_ca_hr_payroll for salary rules computation.

### CODE REVIEW

**Comment by max3903** [comment]
:+1: 

Not sure to understand the Travis error.

**Comment by ghost** [comment]
Not sure either. It seems unrelated to the canadian payroll.

**Comment by bwrsandman** [comment]
See https://github.com/OCA/l10n-canada/issues/25 and solution https://github.com/OCA/l10n-canada/pull/26

**Comment by bwrsandman** [comment]
:+1: LGTM

**Pull request merged**
