### PR TITLE
removed salary_rule record because it makes hr_payroll_account test fail

### LINKED ISSUE #25: l10n_ca_hr_payroll_account fails tests
l10n_ca_hr_payroll_account fails tests when installed and tested on its own.

As a result, all tests on this repo are broken.
https://travis-ci.org/OCA/l10n-canada/jobs/37391299#L493

Todo when done: re-enable `UNIT_TEST` in .travis.yml

### PR DESCRIPTION
**Pull request by ghost**
Removed salary_rule record because it makes hr_payroll_account test fail

Closes #25

### CODE REVIEW

**Comment by bwrsandman** [comment]
Is this the best solution? Isn't this a regression?

**Comment by ghost** [comment]
The file hr_payroll_data.xml will soon be removed in a further commit. The rule record that I removed will not be used.

**Comment by ghost** [comment]
I mean the file l10n_ca_hr_payroll_data.xml

**Comment by bwrsandman** [comment]
Rebase on top of savoirfairelinux:shared_fix and take this line out of comments and the comment:

https://github.com/OCA/l10n-canada/pull/26/files#diff-354f30a63fb0907d4ad57269548329e3R9

**Comment by bwrsandman** [comment]
:+1: Thank you for your hard work figuring out this bug.

**Comment by max3903** [comment]
:+1:

**Pull request merged**
