### PR TITLE
[IMP] Check writing remove chk seq

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Comment by max3903** [comment]
:+1: 

Travis error related to wkhtmltopdf used by another module

**Comment by bwrsandman** [comment]
Needs a rebase

**Comment by pedrobaeza** [comment]
Is this going to be worked on or may I close it?

**Comment by pedrobaeza** [comment]
As there's no answer, I close. Feel free to reopen in case there's interest.

**Pull request closed without merging**
