### PR TITLE
Add module l10n_ca_qc_hr_releve_1

### PR DESCRIPTION
**Pull request by ghost**
This module adds the production of the Relevé 1 slip of revenu Québec.

### CODE REVIEW

**Comment by max3903** [comment]
Please add the report to l10n_ca_qc_hr_payroll module (in a subdirectory named report).

Are you sure it is called releve_1 in english ?

**Comment by ghost** [comment]
@max3903 Revenu Québec does not translate Relevé 1 and the report must be produced only in french. For example, see http://www.revenuquebec.ca/en/sepf/formulaires/rl/rl-1/default.aspx

If I move the report into l10n_ca_qc_hr_payroll/report, then I need to merge l10n_ca_qc_hr_releve_1 and l10n_ca_qc_hr_payroll together. I think these modules have different purposes and need to be separate.

**Comment by max3903** [comment]
@dufresnedavid the purpose is the same: do the quebec payroll. You can't say you do it if you don't have both the rules and the report (payslip and end of year report like the Relevé 1). 

Take the accounting module for example, it provides accounts, journals, taxes, fiscal positions and reports (balance sheet, profit and loss).

In addition that, it is not a report meant to be customized. People won't have the choice to install the payroll module with another report.

**Comment by ghost** [comment]
@max3903 Ok, I will cancel this PR and merge the 2 modules. Thanks

**Pull request closed without merging**
