### PR TITLE
[8.0] Port SIN module

### PR DESCRIPTION
**Pull request by Ehtaga**

### CODE REVIEW

**Comment by max3903** [comment]
Be careful. This module has been changed in the 7.0 branch since the copy in the 8.0 branch.
https://github.com/OCA/l10n-canada/tree/7.0/res_partner_attributes_add_SIN

**Comment by max3903** [comment]
Tested on runbot.

:+1:

**Comment by gurneyalex** [comment]
CLA ok

**Comment by bwrsandman** [comment]
Looks good to me! :+1:

**Pull request merged**
